### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by BelphegorPrime** [gopherds/resources#21]
Hi, 

after clicking the slack link (Gophers Slack #data-science Channel) I will only get to the login site but there is actual no way to login.

greetings

**Comment by bradleyfalzon** [comment]
Do you mean you have no way to signup? If so, you can get the invite here: https://invite.slack.golangbridge.org/

**Comment by BelphegorPrime** [comment]
well shouldn there be some kind of link in a readme?
