### ISSUE TITLE
Possible package that can be included

### ISSUE THREAD

**Issue by kelvins** [gopherds/resources#26]
I have developed a Go package that may be included in the [tooling resources](https://github.com/gopherdata/resources/tree/master/tooling):

[github.com/kelvins/chronobiology](https://github.com/kelvins/chronobiology) - Provide an easy way to access some chronobiology functions that can perform data analysis in time series using GoLang. (I think this is related to bioinformatics)

I don't know if this package is 'robust' as the packages shared in the [tooling resources](https://github.com/gopherdata/resources/blob/master/tooling/README.md#bioinformatics). If you think it should be added feel free to add or let me know.

Thanks

**Comment by dwhitena** [comment]
Yes, we should definitely add.  Please PR with a relevant description to the tooling README.  Thanks!

**Comment by kelvins** [comment]
Ok, I will do that. Thank you so much.

**Comment by dwhitena** [comment]
Added.  Closing.  Thanks!
