### ISSUE TITLE
No data frames or data.table

### ISSUE THREAD

**Issue by vikram-rawat** [gopherds/resources#29]
First job of a data analyst is finding something new. If on that moment he start to write too many codes he would not be able to focus on data...

I know this from experience. This is the reason despite being slow people slip prefer R over python.

Go needs a library like data.table in R and a ggvis package... If you can create just these 2 packages we can start taking go seriously. For the time being i would still stuck to R unless somebody creates this...

Packages like GoTa are not good even at a basic task of selecting multiple rows from dataframes. Or group them by a unique value. 

It would take at least a decade for go to come as a data analysis tool...

But yes once the model is ready once we have findings than go can be used. I am still not sure how but it can be used...

Kindly reply me if you have a better solution.

**Comment by vikram-rawat** [comment]
Try to understand most of the data analyst are not programmer but come from backgrounds like mba, cfa, physiology, economics, statistics, etc etc....

We need a simpler way to look and test the data. Speed is secondary. Is just been a month i started learning go. It easy but i don't know any package which can actually help us in being like data.table in R. Is fast and easy and you don't need anything else till you have it... Just try using that with ggvis and you would understand what i mean...


Does go had anything similar please let me know i would be more than interesting to learn

**Comment by dwhitena** [comment]
@vikram-rawat Go definitely has dataframes.  Have you tried https://github.com/kniren/gota.  Not full parity with data.table or pandas yet, but it's a really great project!

**Comment by dwhitena** [comment]
Closing for now.
